server.port=8082
spring.application.name=ms-pedidos

# URL de ms-inventario dentro de Docker Compose
# Fuera de Docker usa localhost, dentro usa el nombre del servicio
inventario.service.url=${INVENTARIO_SERVICE_URL:http://localhost:8080}